import numpy as np


def crossover(chromosomes):
    """
    Takes a numpy array of two chromosome instances and performs a crossover operation between them.
    Args:
        chromosomes -> Numpy array of Chromosome class instances of size 2
    Returns:
        children -> Numpy array of 2 offsprings generated by the crossover operation 
    """
    children = np.array([])

    return children