from abc import ABC, abstractmethod
import numpy as np
from copy import deepcopy as dcp

from genetic_algorithm.utils.helpers import ensure_np_array


class OperatorBase(ABC):
    
    @abstractmethod
    def crossover(self):
        pass

    @abstractmethod
    def mutate(self):
        pass


class Operator(OperatorBase):
    def crossover(self, chromosomes, crossover_type, args={}):
        """
        Takes a numpy array of two chromosome instances and performs a crossover operation between them.
        Args:
            chromosomes -> Numpy array of Chromosome class instances of size 2
            crossover_type -> String. Must be one of ['uniform', 'single_point', 'multiple_points', 'user_defined']
        Returns:
            children -> Numpy array of 2 offsprings generated by the crossover operation 
        """

        if crossover_type == "single-point":
            try:
                cutoff = args["cutoff_proportion"]
            except(KeyError):
                cutoff = np.random.uniform()
            
            children = _uniform_crossover(chromosomes, cutoff)
        
        return children

    def _uniform_crossover(self, chromosomes, cutoff):
        chromosome1, chromosome2 = chromosomes[0], chromosomes[1]
        length = len(chromosome1.genotype)
        cutoff_idx = int(length * cutoff)

        gen1 = chromosome1.genotype
        gen2 = chromosome2.genotype

        hold1 = dcp(gen1[cutoff_idx:])
        hold2 = dcp(gen2[cutoff_idx:])
        gen1[cutoff_idx:] = hold2
        gen2[cutoff_idx:] = hold1

        chromosome1.genotype = gen1
        chromosome2.genotype = gen2

        children = ensure_np_array([chromosome1, chromosome2])

        return children

    def mutate(self):
        pass